title:            Parker Technical Sales
description:      Fluid Solutions
# TODO: add back in once new version created
# logo:             pts-logo.png
disqus_shortname:
search:           false
# Change url to your domain. Leave localhost server or blank when working locally.
# url:              http://localhost:4000
url: http://www.parkertechnicalsales.com

# Owner/author information
owner:
  name:           Parker Technical Sales
  avatar:         bio-photo.jpg
  email:          sales@parkertechnicalsales.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:
  facebook:
  github:
  stackexchange:
  linkedin:
  instagram:
  flickr:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-60211561-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Products
    url: /products/
  - title: Manufacturers
    url: /manufacturers/
  - title: Contact
    url: /contact/
  - title: Request a Quote
    url: /contact/#form

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Los_Angeles
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

gems:
  - jekyll-redirect-from

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
